### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by klaemo** [developit/preact-css-transition-group#2]
Hey there,
could you please publish the latest version to npm?
The one currently on npm pulls in `preact@5.7.0` as a dep and doesn't work with `preact6.x` anymore.

Thank you so much!

**Comment by developit** [comment]
Published as [1.1.0](https://github.com/developit/preact-css-transition-group/releases/tag/1.1.0)!

**Comment by klaemo** [comment]
❤️ thank you! another step closer towards using preact in our project :)
