### ISSUE TITLE
Transition animation not being called with Preact-Router

### ISSUE THREAD

**Issue by AdamJo** [developit/preact-css-transition-group#6]
Running into issues with router transitions.  React dev tools is showing that CSSTransitionGroup has been loaded but nothing is triggering the route animations.

```
        <CSSTransitionGroup
              transitionName='example'
            >
            {this.props.children}
	</CSSTransitionGroup>
```

I [setup a test repo](https://github.com/AdamJo/preact-router-transition) for CSSmodules and SCSS if you want to check it out.

**Comment by developit** [comment]
@AdamJo Are you able to test without `preact/devtools` enabled?

**Comment by AdamJo** [comment]
@developit Tried commenting out `preact/devtools`, no change so far.  The `span` is being created but no sign of the `enter` / `leave` classes being called.

**Comment by developit** [comment]
Ok, good to know. What is being rendered as the child of this component?  Would be useful to know if it's a pure functional component, a regular component, or an element.

**Comment by AdamJo** [comment]
They are 4 pure functional components. I also tested with a class component but got the same results.

**Comment by AdamJo** [comment]
I was able to find this guy's work that helped https://github.com/nerijusgood/ng.

Turns out I was passing in my component into CSSTransitionGroup wrong.  I'll go ahead and close this issue now that I've got it working.
